#ifndef POKEMON_ID_LIST_H
#define POKEMON_ID_LIST_H

typedef enum { POKEMON_MISSING_NO, POKEMON_BULBASAUR, POKEMON_IVYSAUR, POKEMON_VENUSAUR, POKEMON_CHARMANDER, 
    POKEMON_CHARMELEON, POKEMON_CHARIZARD, POKEMON_SQUIRTLE, POKEMON_WARTORTLE, POKEMON_BLASTOISE, POKEMON_CATERPIE, 
    POKEMON_METAPOD, POKEMON_BUTTERFREE, POKEMON_WEEDLE, POKEMON_KAKUNA, POKEMON_BEEDRILL, POKEMON_PIDGEY, 
    POKEMON_PIDGEOTTO, POKEMON_PIDGEOT, POKEMON_RATTATA, POKEMON_RATICATE, POKEMON_SPEAROW, POKEMON_FEAROW, 
    POKEMON_EKANS, POKEMON_ARBOK, POKEMON_PIKACHU, POKEMON_RAICHU, POKEMON_SANDSHREW, POKEMON_SANDSLASH, 
    POKEMON_NIDORAN_F, POKEMON_NIDORINA, POKEMON_NIDOQUEEN, POKEMON_NIDORAN_M, POKEMON_NIDORINO, POKEMON_NIDOKING, 
    POKEMON_CLEFAIRY, POKEMON_CLEFABLE, POKEMON_VULPIX, POKEMON_NINETALES, POKEMON_JIGGLYPUFF, POKEMON_WIGGLYTUFF, 
    POKEMON_ZUBAT, POKEMON_GOLBAT, POKEMON_ODDISH, POKEMON_GLOOM, POKEMON_VILEPLUME, POKEMON_PARAS, POKEMON_PARASECT, 
    POKEMON_VENONAT, POKEMON_VENOMOTH, POKEMON_DIGLETT, POKEMON_DUGTRIO, POKEMON_MEOWTH, POKEMON_PERSIAN, POKEMON_PSYDUCK, 
    POKEMON_GOLDUCK, POKEMON_MANKEY, POKEMON_PRIMEAPE, POKEMON_GROWLITHE, POKEMON_ARCANINE, POKEMON_POLIWAG, 
    POKEMON_POLIWHIRL, POKEMON_POLIWRATH, POKEMON_ABRA, POKEMON_KADABRA, POKEMON_ALAKAZAM, POKEMON_MACHOP, POKEMON_MACHOKE, 
    POKEMON_MACHAMP, POKEMON_BELLSPROUT, POKEMON_WEEPINBELL, POKEMON_VICTREEBEL, POKEMON_TENTACOOL, POKEMON_TENTACRUEL, 
    POKEMON_GEODUDE, POKEMON_GRAVELER, POKEMON_GOLEM, POKEMON_PONYTA, POKEMON_RAPIDASH, POKEMON_SLOWPOKE, POKEMON_SLOWBRO, 
    POKEMON_MAGNEMITE, POKEMON_MAGNETON, POKEMON_FARFETCHD, POKEMON_DODUO, POKEMON_DODRIO, POKEMON_SEEL, POKEMON_DEWGONG, 
    POKEMON_GRIMER, POKEMON_MUK, POKEMON_SHELLDER, POKEMON_CLOYSTER, POKEMON_GASTLY, POKEMON_HAUNTER, POKEMON_GENGAR, POKEMON_ONIX, 
    POKEMON_DROWZEE, POKEMON_HYPNO, POKEMON_KRABBY, POKEMON_KINGLER, POKEMON_VOLTORB, POKEMON_ELECTRODE, POKEMON_EXEGGCUTE, 
    POKEMON_EXEGGUTOR, POKEMON_CUBONE, POKEMON_MAROWAK, POKEMON_HITMONLEE, POKEMON_HITMONCHAN, POKEMON_LICKITUNG, POKEMON_KOFFING, 
    POKEMON_WEEZING, POKEMON_RHYHORN, POKEMON_RHYDON, POKEMON_CHANSEY, POKEMON_TANGELA, POKEMON_KANGASKHAN, POKEMON_HORSEA, 
    POKEMON_SEADRA, POKEMON_GOLDEEN, POKEMON_SEAKING, POKEMON_STARYU, POKEMON_STARMIE, POKEMON_MR_MIME, POKEMON_SCYTHER, 
    POKEMON_JYNX, POKEMON_ELECTABUZZ, POKEMON_MAGMAR, POKEMON_PINSIR, POKEMON_TAUROS, POKEMON_MAGIKARP, POKEMON_GYARADOS, 
    POKEMON_LAPRAS, POKEMON_DITTO, POKEMON_EEVEE, POKEMON_VAPOREON, POKEMON_JOLTEON, POKEMON_FLAREON, POKEMON_PORYGON, 
    POKEMON_OMANYTE, POKEMON_OMASTAR, POKEMON_KABUTO, POKEMON_KABUTOPS, POKEMON_AERODACTYL, POKEMON_SNORLAX, POKEMON_ARTICUNO, 
    POKEMON_ZAPDOS, POKEMON_MOLTRES, POKEMON_DRATINI, POKEMON_DRAGONAIR, POKEMON_DRAGONITE, POKEMON_MEWTWO, POKEMON_MEW
} Pokemon_id;


#endif //POKEMON_ID_LIST_H