#ifndef PRINT_DEFINES_H
#define PRINT_DEFINES_H

#define BATTLE_BOX_X 3
#define BATTLE_BOX_Y 2
#define BATTLE_BOX_WIDTH 50
#define BATTLE_BOX_HEIGHT 7

#define TEXT_BOX_X BATTLE_BOX_X
#define TEXT_BOX_Y (BATTLE_BOX_Y + BATTLE_BOX_HEIGHT)
#define TEXT_BOX_WIDTH 50
#define TEXT_BOX_HEIGHT 10

#define BATTLE_SELECT_1_X (TEXT_BOX_X + 1)
#define BATTLE_SELECT_2_X (TEXT_BOX_X + 19)
#define BATTLE_SELECT_3_X (TEXT_BOX_X + 37)
#define SELECT_Y TEXT_BOX_Y + 1

#endif // PRINT_DEFINES_H